import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.scss'
import NavBar from '@/components/NavBar'
import Card from '@/components/Card'

export default function Home() {
  return (
    <>

      <div className={styles.Hero}>
        <Head>
          <title>Wrap N Go</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <NavBar />

        <div className={styles.Container}>
          <h1 className={styles.Title}>Get what you’re craving</h1>
          <button className={styles.SearchBox}>

            <svg className={styles.SearchIcon} xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 40 40" fill="none">
              <path d="M28.9946 27.5126C35.4745 19.9491 29.866 7.91721 19.8859 8.00049C16.7349 8.00402 13.7139 9.25733 11.4858 11.4855C9.25768 13.7136 8.00438 16.7346 8.00088 19.8856C7.88151 29.8463 19.9693 35.4796 27.5102 28.9923L33.5179 35.0001L35 33.518L28.9946 27.5126ZM12.9742 26.8149C6.81013 20.7787 11.2524 10.0374 19.8863 10.0967C22.4816 10.0996 24.9697 11.1318 26.8049 12.967C28.64 14.8022 29.6722 17.2903 29.6751 19.8856C29.7594 28.4971 19.0098 32.9552 12.9742 26.8149Z" fill="black" />
            </svg>
            <p className={styles.Label}>Search your favoutite food</p>
          </button>
        </div>

      </div>

      <div className={styles.Dishes}>
        <Card/>
      </div>
    </>
  )
}
